### ISSUE TITLE
tesseract 启动错误

### ISSUE THREAD

**Issue by kisskevin** [Baidu-ecom/bi-platform#118]
[2015-05-25 14:47:04254 ERROR]--main--Http11NioProtocol: Failed to start end poi
nt associated with ProtocolHandler ["http-nio-8099"]
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:343)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.ja
va:737)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:471)
        at org.apache.coyote.http11.Http11NioProtocol.start(Http11NioProtocol.ja
va:80)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:
986)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardService.addConnector(StandardService
.java:237)

**Comment by totyumengr** [comment]
8099端口被占用？

**Comment by kisskevin** [comment]
是的，8099是我配置application.properties的端口:(server.port=8099 －－－－ designer 端口配置，默认可以省略) 先启动了designer

**Comment by totyumengr** [comment]
从异常看，还是端口占用啊。换一个其他端口可以么？

**Comment by wangyuxue** [comment]
从异常信息看是端口被占用。解决步骤：
1.排查是否使用该端口，如使用请更换端口
2.确认启动过程spring能够扫描到application.properties。tesseract的配置文件为（tesseract.properties）
3.可以直接在启动命令中添加：-Dserver.port=8099

**Comment by kisskevin** [comment]
端口是在application.properties中配置的，先启动designer则tesseract报错说端口占用，先启动tesseract则designer报错说端口占用 。 designer启动时指定其它端口 仍然会读取application.properties中的配置

**Comment by kisskevin** [comment]
机器上装了VMWARE 但是没有启动，在启动designer或者tesseract时会读取虚拟机网卡的地址信息，请问这个是做什么用的？集群吗？我注释掉了所有有关redis的配置，对启动有影响吗？

**Comment by wangyuxue** [comment]
BiPlatform缓存采用插拔式配置方案，默认会启用hz的缓存。注释掉redis对缓存使用没有影响。designer或tesseract启动时读取网卡地址信息是由于：对于线下环境，为更好维护缓存，线下环境缓存key统一采用mac地址作为前缀。

**Comment by wangyuxue** [comment]
端口是在application.properties中配置的，先启动designer则tesseract报错说端口占用，先启动tesseract则designer报错说端口占用 。 designer启动时指定其它端口 仍然会读取application.properties中的配置：关于这个问题，建议你删除掉application.properties中的配置，在启动命令行中添加：-Dserver.port=xxxx.
你这里之所以出现这个问题，是因为你的designer和tesseract公用了一份application.properties

**Comment by kisskevin** [comment]
在ECLIPSE里成功启动了工程。designer 的参数是 -Dserver.port=8099 为什么页面访问时端口号是tomcat默认的8080，这个参数指定的端口有什么用？ Tesseract 启动时 Dserver.port=9191 ，那么ac.properties 里面也配置成 9191吧？

**Comment by wangyuxue** [comment]
@kisskevin -Dserver.port配置的是启动服务的端口，如果用在designer上，就是配置的designer服务的端口，其他类推。如果Tesseract启动时是9191，那ac.properties中配置的就是9191

**Comment by kisskevin** [comment]
通过参数 -Dserver.port=8099 -Dac.config.location=E:\baidu_bi\installed\ac.properties 在ECLIPSE中启动DESIGNER 控制台打出TOMCAT的访问端口仍然是8080 ，第二个参数在设计好表的行轴、列轴后查询出错，原因是model工程里读这个参数时是空。

**Comment by wangyuxue** [comment]
你好，这个问题已经收录，我们会尽快解决，谢谢！
