### ISSUE TITLE
启动报错：

### ISSUE THREAD

**Issue by junphine** [Baidu-ecom/bi-platform#126]
[INFO]************begin start tesseract
Exception in thread "main" java.lang.NoClassDefFoundError: EmbeddedServletConta
nerFactory
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2688)
        at java.lang.Class.getDeclaredMethod(Class.java:2115)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunne
.java:48)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.ClassNotFoundException: EmbeddedServletContainerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(L
unchedURLClassLoader.java:170)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(Lau
chedURLClassLoader.java:136)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more

**Comment by wangyuxue** [comment]
你好，请描述一下你那里的运行环境
