### ISSUE TITLE
1.6.0,  1.7.0  组件schedule、designer、tesseract构建失败

### ISSUE THREAD

**Issue by hurricanetx** [Baidu-ecom/bi-platform#139]
1.6.0,  1.7.0  组件schedule、designer、tesseract构建失败， 是缺少什么文件吗？

亲，能不能出手放一个编译好的文件包，让大家感受一下魅力

**Comment by wangyuxue** [comment]
你好，缺失文件已经补充，感谢提醒

**Comment by hurricanetx** [comment]
okay编译成功了，直接在根目录编译是不行的；

应该按照依赖顺序编译：
cache -> parser  ->   fileserver
model  -> common-api  ->  schedule  ->  designer
tesseract  -> queryrouter

编译命令
mvn install

如果编译失败以下两条
mvn clean
mvn install -Dmaven.test.skip=true

**Comment by hurricanetx** [comment]
@wangyuxue 亲，现在编译okay，也部署了，启动的时候报错，能看下啥问题不

 Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.io.FileNotFoundException: 9090 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.baidu.rigel.biplatform.ma.file.serv.FileServer.main(FileServer.java:133)

**Comment by wangyuxue** [comment]
你好，启动错误是由于fileserver的启动参数有问题。fileserver启动参数为fileserver基本配置文件，具体文件格式可以参考：filerver.comf.tmp：
biplatform.fileserver.rootdir=/report
biplatform.fileserver.port=9090

假设将此文件存储在／目录：
启动如下：
java -jar /opt/bi/bin/fileserver-1.7.0-SNAPSHOT.jar ／report >/opt/bi/log/fileserver.log&

**Comment by hurricanetx** [comment]
@wangyuxue ^_^ 修改一下 readme.md吧，把配置那块儿修改一下吧，传入的是配置文件，而不是端口和路径；

目前是运行成功了，但是访问8999，9090 均没有看到界面，是因为数据还需要配置么？

以下信息留给其他朋友：

将fileserver.conf  写入：
biplatform.fileserver.rootdir=/opt/bi/report
biplatform.fileserver.port=9090

启动脚本修改为：
启动脚本:
java -jar /opt/bi/bin/fileserver-1.7.0-SNAPSHOT.jar /opt/bi/fileserver.conf > /opt/bi/log/fileserver.log &
java -jar /opt/bi/bin/tesseract-1.7.0-SNAPSHOT.jar > /opt/bi/log/ter.log &
java -jar /opt/bi/bin/designer-1.7.0-SNAPSHOT.jar --server.port=8999 > /opt/bi/log/designer.log &
echo "fileserver 9090 | designer 8999"

仍然提示，某模块加载失败
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Aug 31, 2015 2:44:38 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFO: [id: 0x34aafac2] REGISTERED
Aug 31, 2015 2:44:38 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0x34aafac2] BIND: 0.0.0.0/0.0.0.0:9090

**Comment by wangyuxue** [comment]
多谢提醒，readme.md是1.0.0版的，后续升级对那里做过调整，未及时更新。非常感谢

**Comment by swallowjy** [comment]
[root@host2 bi]# java -jar fileserver-1.7.0-SNAPSHOT.jar /usr/lib/bi/fileserver.conf.tmp
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sep 22, 2015 1:44:20 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFO: [id: 0xf1e719b2] REGISTERED
Sep 22, 2015 1:44:20 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0xf1e719b2] BIND: 0.0.0.0/0.0.0.0:9090
Sep 22, 2015 1:44:20 PM io.netty.handler.logging.LoggingHandler channelActive
INFO: [id: 0xf1e719b2, /0:0:0:0:0:0:0:0:9090] ACTIVE
然后就木有反应了，求解答  Centos6.7 + Maven 3.0.5 + JDK8 + BIplatform1.7

**Comment by hurricanetx** [comment]
@swallowjy 这个应该是正常启动了吧。我们应该访问的是 tesseract 的服务； fileserver 应该只是负责把报告存在 某个目录下而已

**Comment by swallowjy** [comment]
这样呀，designer application.properties的配置http://my.oschina.net/biplatform/blog/412942?p=2按照这个配就可以了吗，我没有装redis和ActiveMQ，配置文件默认就可以了吗，127.0.0.1需要改成自己机器的IP地址吗，不是很懂，谢谢~~

**Comment by swallowjy** [comment]
我用的默认配置，启动designer时出错
boot - 12041 ERROR [regularReportTaskConsumerMessageListenerContainer-1] --- DefaultMessageListenerContainer: Could not refresh JMS Connection for destination 'queue://regularReportTaskQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=678, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not connect to broker URL: tcp://127.0.0.1:61616. Reason: java.net.ConnectException: Connection refused

**Comment by swallowjy** [comment]
启动tesseract，又不动了，这是成功了吗？
[2015-09-22 16:13:42583 INFO]--main--InternalPartitionService: [192.168.137.110]:5701 [silkroad-group] [3.2.3] Initializing cluster partition table first arrangement... 
[2015-09-22 16:13:42613 INFO]--main--IndexMetaServiceImpl:  loadIndexMetasLocalImage: [params:[idxBaseDir:D:/tesseract_data_0/indexbase/][currNodeKey:NODEKEY_CLUSTER_NAME_DEFAULT_192.168.137.110_9988][clusterName:CLUSTER_NAME_DEFAULT]] start  
[2015-09-22 16:13:42617 INFO]--main--IndexMetaServiceImpl:  recoverLocalIndexMetaWithCluster: [params:[idxMetaList.size:null][clusterName:CLUSTER_NAME_DEFAULT]] start  
[2015-09-22 16:13:42621 INFO]--main--IndexMetaServiceImpl:  recoverLocalIndexMetaWithCluster: [params:[idxMetaList.size:null][clusterName:CLUSTER_NAME_DEFAULT]] end  
[2015-09-22 16:13:42653 INFO]--main--Http11Nio2Protocol: Initializing ProtocolHandler ["http-nio2-8090"] 
[2015-09-22 16:13:42664 INFO]--main--Http11Nio2Protocol: Starting ProtocolHandler ["http-nio2-8090"] 
[2015-09-22 16:13:42685 INFO]--main--TomcatEmbeddedServletContainer: Tomcat started on port(s): 8090 (http) 
[2015-09-22 16:13:42686 INFO]--main--TesseractApplication: Started TesseractApplication in 14.707 seconds (JVM running for 16.404)

**Comment by wangyuxue** [comment]
是的，已经启动成功了 Started TesseractApplication in 14.707 seconds (JVM running for 16.404)

**Comment by swallowjy** [comment]
为什么启动成功后就是木有反应的状态了，正常不是应该退出到命令行然后以进程的形式存在吗？

**Comment by yuchaozhou** [comment]
@swallowjy 这不关乎BI的事了，想做到后台service形式，你自己写下就OK，如linux 下带执行时，最后带上'&'

**Comment by totyumengr** [comment]
对，类似这种。nohup java -server ***.jar > ***.log 2>&1 &

**Comment by swallowjy** [comment]
@totyumengr @yuchaozhou 后来我知道了，谢谢大家~~

**Comment by heropiant** [comment]
感觉这个项目的管理很混乱，版本之间经常缺文件，说明文档滞后，sh文件是dos格式，登录帐号没有说明，等等。。
问题很多呀。。

**Comment by wangyuxue** [comment]
@heropiant  你好，本项目文档已经发布，可以在wiki链接中下载，登录账号需要自己采用注册方式自助提供
感谢关注和支持
