### ISSUE TITLE
mvn install报错，请帮忙看下怎么处理

### ISSUE THREAD

**Issue by princes1** [Baidu-ecom/bi-platform#140]
[INFO] Building tesseract 1.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.baidu.rigel.biplatform:cache:jar:1.7.0-SNAPSHOT is missing, no dependency information availabl
e
[WARNING] The POM for com.baidu.rigel.biplatform:model:jar:1.7.0-SNAPSHOT is missing, no dependency information availabl
e
[WARNING] The POM for com.baidu.rigel.biplatform:parser:jar:0.0.1-SNAPSHOT is missing, no dependency information availab
le
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.724s
[INFO] Finished at: Sat Aug 29 14:35:19 CST 2015
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tesseract: Could not resolve dependencies for project com.baidu.rigel.biplatfo
rm:tesseract:jar:1.7.0-SNAPSHOT: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:1.7
.0-SNAPSHOT, com.baidu.rigel.biplatform:model:jar:1.7.0-SNAPSHOT, com.baidu.rigel.biplatform:parser:jar:0.0.1-SNAPSHOT:
Could not find artifact com.baidu.rigel.biplatform:cache:jar:1.7.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by wangyuxue** [comment]
构建时候skip test 试试

**Comment by princes1** [comment]
不行 在fileserver下可以  在designer下建不行 ，在主目录下直接建业不可以

[root@localhost designer]# mvn install -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.baidu.rigel.biplatform:designer:jar:1.7.0-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.powermock:powermock-api-mockito:jar -> duplicate declaration of version ${org.powermock.version} @ com.baidu.rigel:biplatform:1.7.0-SNAPSHOT, /root/bi-platform-branch_1.7.0/pom.xml, line 263, column 25
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building designer 1.7.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.baidu.rigel.biplatform:cache:jar:1.7.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.baidu.rigel.biplatform:schedule:jar:1.7.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.baidu.rigel.biplatform:common-api:jar:1.7.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for com.baidu.rigel.biplatform:model:jar:1.7.0-SNAPSHOT is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-log4j/1.2.3.RELEASE/spring-boot-starter-log4j-1.2.3.RELEASE.pom
Downloaded: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-log4j/1.2.3.RELEASE/spring-boot-starter-log4j-1.2.3.RELEASE.pom (2 KB at 1.3 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/com/h2database/h2/1.4.185/h2-1.4.185.pom
Downloaded: http://repo.maven.apache.org/maven2/com/h2database/h2/1.4.185/h2-1.4.185.pom (966 B at 2.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.pom
Downloaded: http://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.pom (2 KB at 3.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.pom
Downloaded: http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.pom (2 KB at 2.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4.1/mail-1.4.1.pom
Downloaded: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4.1/mail-1.4.1.pom (995 B at 2.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.pom
Downloaded: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.pom (2 KB at 2.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/velocity/velocity/1.7/velocity-1.7.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/velocity/velocity/1.7/velocity-1.7.pom (11 KB at 25.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-log4j/1.2.3.RELEASE/spring-boot-starter-log4j-1.2.3.RELEASE.jar
Downloading: http://repo.maven.apache.org/maven2/com/h2database/h2/1.4.185/h2-1.4.185.jar
Downloading: http://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.jar
Downloading: http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar
Downloading: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4.1/mail-1.4.1.jar
Downloaded: http://repo.maven.apache.org/maven2/org/json/json/20090211/json-20090211.jar (45 KB at 73.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.jar
Downloaded: http://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-log4j/1.2.3.RELEASE/spring-boot-starter-log4j-1.2.3.RELEASE.jar (3 KB at 3.2 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/velocity/velocity/1.7/velocity-1.7.jar
Downloaded: http://repo.maven.apache.org/maven2/javax/activation/activation/1.1/activation-1.1.jar (62 KB at 110.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/javax/mail/mail/1.4.1/mail-1.4.1.jar (438 KB at 190.1 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/apache/velocity/velocity/1.7/velocity-1.7.jar (439 KB at 220.8 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.34/mysql-connector-java-5.1.34.jar (938 KB at 64.9 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/com/h2database/h2/1.4.185/h2-1.4.185.jar (1648 KB at 38.7 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.466s
[INFO] Finished at: Mon Aug 31 10:11:11 CST 2015
[INFO] Final Memory: 11M/83M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project designer: Could not resolve dependencies for project com.baidu.rigel.biplatform:designer:jar:1.7.0-SNAPSHOT: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:1.7.0-SNAPSHOT, com.baidu.rigel.biplatform:schedule:jar:1.7.0-SNAPSHOT, com.baidu.rigel.biplatform:common-api:jar:1.7.0-SNAPSHOT, com.baidu.rigel.biplatform:model:jar:1.7.0-SNAPSHOT: Could not find artifact com.baidu.rigel.biplatform:cache:jar:1.7.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by wangyuxue** [comment]
你好，构建时需要在项目目录下直接构建，如要打包指定子项目，需要按照model、cache、filserver、commonapi、scheduler、tesseract、designer顺序构建

**Comment by princes1** [comment]
在项目目录上构建也有报错。
[root@localhost bi-platform]# mvn install -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.baidu.rigel.biplatform:fileserver:jar:1.7.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: commons-lang:commons-lang:jar -> duplicate declaration of version (?) @ line 45, column 21
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.powermock:powermock-api-mockito:jar -> duplicate declaration of version ${org.powermock.version} @ com.baidu.rigel:biplatform:1.7.0-SNAPSHOT, /home/user/git/bi-platform/pom.xml, line 263, column 25
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 20 source files to /home/user/git/bi-platform/schedule/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[29,42] 找不到符号
  符号: 类 BaseScheduleJob
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[29,8] com.baidu.rigel.biplatform.schedule.job.HttpClientExcuteJob不是抽象的, 并且未覆盖org.quartz.Job中的抽象方法execute(org.quartz.JobExecutionContext)
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[48,5] 方法不会覆盖或实现超类型的方法
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[105,5] 方法不会覆盖或实现超类型的方法
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] bi-platform ....................................... SUCCESS [1.175s]
[INFO] fileserver ........................................ FAILURE [7.367s]
[INFO] model ............................................. SKIPPED
[INFO] cache ............................................. SKIPPED
[INFO] common-api ........................................ SKIPPED
[INFO] schedule .......................................... SKIPPED
[INFO] designer .......................................... SKIPPED
[INFO] parser ............................................ SKIPPED
[INFO] tesseract ......................................... SKIPPED
[INFO] queryrouter ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.289s
[INFO] Finished at: Tue Sep 01 12:36:42 CST 2015
[INFO] Final Memory: 38M/92M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project schedule: Compilation failure: Compilation failure:
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[29,42] 找不到符号
[ERROR] 符号: 类 BaseScheduleJob
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[29,8] com.baidu.rigel.biplatform.schedule.job.HttpClientExcuteJob不是抽象的, 并且未覆盖org.quartz.Job中的抽象方法execute(org.quartz.JobExecutionContext)
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[48,5] 方法不会覆盖或实现超类型的方法
[ERROR] /home/user/git/bi-platform/schedule/src/main/java/com/baidu/rigel/biplatform/schedule/job/HttpClientExcuteJob.java:[105,5] 方法不会覆盖或实现超类型的方法
[ERROR] -> [Help 1]

**Comment by princes1** [comment]
[ERROR] Failed to execute goal on project tesseract: Could not resolve dependencies for project com.baidu.rigel.biplatform:tesseract:jar:1.7.0-SNAPSHOT: Could not transfer artifact org.springframework:spring-jdbc:jar:4.1.6.RELEASE from/to central (http://repo.maven.apache.org/maven2): GET request of: org/springframework/spring-jdbc/4.1.6.RELEASE/spring-jdbc-4.1.6.RELEASE.jar from central failed: Connection reset -> [Help 1]

我又重新弄了一遍是资源库里找不到相应jar包呀

**Comment by hurricanetx** [comment]
mvn install -Dmaven.test.skip=true

**Comment by princes1** [comment]
制作㎡报表的时候报错，端口或者进程启动点的不对？
[2015-09-06 15:54:46.215] boot - 21006  INFO [http-nio-8999-exec-10] --- HttpRequest: generate route : {}->http://127.0.0.1:8080
[2015-09-06 15:54:46.216] boot - 21006  INFO [http-nio-8999-exec-10] --- HttpRequest: generate route : {}->http://127.0.0.1:9191
[2015-09-06 15:54:46.289] boot - 21006  INFO [http-nio-8999-exec-10] --- HttpRequest: start to send post:http://[127.0.0.1:8080 127.0.0.1:9191]//query
[2015-09-06 15:54:46.289] boot - 21006  INFO [http-nio-8999-exec-10] --- HttpRequest: post url is : http://127.0.0.1:8080//query
[2015-09-06 15:54:46.319] boot - 21006  INFO [http-nio-8999-exec-10] --- HttpRequest: [INFO] --- --- execute query with client org.apache.http.impl.client.InternalHttpClient@7496949f
[2015-09-06 15:54:46.394] boot - 21006  WARN [http-nio-8999-exec-10] --- HttpRequest: send post error http://[127.0.0.1:8080 127.0.0.1:9191]//query,retry next one
org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8080 [/127.0.0.1] failed: 拒绝连接
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:293)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:313)

**Comment by wangyuxue** [comment]
需要确认tesseract是否正常启动，如端口不正确，需要在ac.properties
中配置

**Comment by zhylninc** [comment]
rigel.biplatform:cache:jar:1.7.0-SNAPSHOT
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        ... 24 more
Caused by: org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.baidu.rigel.biplatform:cache:jar:1.7.0-SNAPSHOT
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:528)
        ... 26 more
