### ISSUE TITLE
根据默认配置，tesseract起动出错

### ISSUE THREAD

**Issue by yuchaozhou** [Baidu-ecom/bi-platform#150]
感谢开源BI套件，试用过程中，出现一些问题，具体信息如下描述，如有不详，请提出我及时补充，感谢！

1、win7 64 java1.8
2、未配置redis,jms，fileserver、designer启动正常，tesseract出错
3、fileserver配置如下：
biplatform.fileserver.rootdir=G:/bi/report
biplatform.fileserver.port=9090
4、application配置文件仅将redis改为false，其它保持当前1.7.0默认
5、tesseract配置文件仅将redis改为false，其它保持当前1.7.0默认
6、启动命令
    java -jar fileserver-1.7.0-SNAPSHOT.jar G:/bi/fileserver.conf

    java -jar designer-1.7.0-SNAPSHOT.jar  -Dac.config.location=G:/bi/ac.properties

   java -jar tesseract-1.7.0-SNAPSHOT.jar  -Xmx1024m -Xms10
24m -Dac.config.location=ac.properties

=============================问题分割线=============================

Q1：在查看配置文件过程中，发现application配置文件有以下配置
server.port=8090
################################################################################################
# schedule service host port 
################################################################################################
biplatform.ma.schedule.host.port=8090
schedule.excuteActionUrlHost=http://127.0.0.1:8090/

以上配置是否会出问题？

Q2：tesseract后台某线程报 端口被占用错误。

=======================错误日志分割线=========================
具体错误日志如下：

[2015-09-27 01:09:02109 INFO]--main--Http11Nio2Protocol: Initializing ProtocolHa
ndler ["http-nio2-8090"]
[2015-09-27 01:09:02132 INFO]--main--Http11Nio2Protocol: Starting ProtocolHandle
r ["http-nio2-8090"]
[2015-09-27 01:09:02162 ERROR]--main--Http11Nio2Protocol: Failed to start end po
int associated with ProtocolHandler ["http-nio2-8090"]
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.AsynchronousServerSocketChannelImpl.bind(Unknown Source)
        at org.apache.tomcat.util.net.Nio2Endpoint.bind(Nio2Endpoint.java:294)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.ja
va:739)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:472)
        at org.apache.coyote.http11.Http11Nio2Protocol.start(Http11Nio2Protocol.
java:76)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:
986)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardService.addConnector(StandardService
.java:237)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServle
tContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:18
6)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServle
tContainer.start(TomcatEmbeddedServletContainer.java:149)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationConte
xt.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:288)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationConte
xt.finishRefresh(EmbeddedWebApplicationContext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationConte
xt.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:946)
        at com.baidu.rigel.biplatform.tesseract.application.TesseractApplication
.main(TesseractApplication.java:64)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:53)
        at java.lang.Thread.run(Unknown Source)
[2015-09-27 01:09:02172 ERROR]--main--StandardService: Failed to start connector
 [Connector[org.apache.coyote.http11.Http11Nio2Protocol-8090]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[org
.apache.coyote.http11.Http11Nio2Protocol-8090]]

**Comment by swallowjy** [comment]
我之前也是这个错误，查看日志发现tesseract启动过程中需要designer占用的那个端口，我是先启动tesseract，再启用designer就成功了。

**Comment by yuchaozhou** [comment]
@swallowjy 恩，先谢谢！ 我修改了application配置文件8090端口，必为其它的，现在正常启动。
bi-platform文档较少，需要我们多多沟。交流QQ群：149225568 欢迎加入：）

**Comment by wangyuxue** [comment]
@yuchaozhou @swallowjy 启动各个服务模块最好提供不同的配置文件，如需更详细的文档，请参考biplatform博客，谢谢！
