### ISSUE TITLE
1.6.1 demo帐号无效，注册帐号也失败

### ISSUE THREAD

**Issue by heropiant** [Baidu-ecom/bi-platform#152]
h2, fileserver, designer, tess都启动成功，进程存在，端口打开。
打开http://server:8090/silkroad/home.html正常。
用demo/demo登录，返回帐号密码错误；自己注册帐号提交返回"请和Administrator反映！"的英文提示。
上述错误发生时，只有designer.log日志文件有更新。错误信息为：

[2015-10-21 16:06:49.459] boot - 3738 ERROR [regularReportTaskConsumerMessageListenerContainer-1] --- DefaultMessageListenerContainer: Could not refresh JMS Connection for destination 'queue://regularReportTaskQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=702, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not connect to broker URL: tcp://127.0.0.1:61616. Reason: java.net.ConnectException: Connection refused

这是要装基于JMS的MQ服务吗？怎么文档里没有说过。

**Comment by wangyuxue** [comment]
JMS的MQ服务可以不安装，目前使用JMS的固定报表功能还没有对用户开放，因此没有提供用户文档。最新版本的平台已经不在提供demo内置帐号，需要自行注册

**Comment by wangyuxue** [comment]
另：注册帐号失败，在文件服务器日志以及designer日志中，都会有相应信息记录原因，麻烦给一下更详细的日志吧

**Comment by heropiant** [comment]
新浪邮箱smtp.sina.com的端口是465，但是designer.properties只有
注册帐号失败，在designer.log中得到如下信息：
[2015-10-23 14:27:51.497] boot - 981  INFO [http-nio-8090-exec-5] --- UniversalContextSettingFilter: current request url : /silkroad/register
[2015-10-23 14:27:51.498] boot - 981  INFO [http-nio-8090-exec-5] --- UniversalContextSettingFilter: productLine in cookie is null and sessio
nId is null[2015-10-23 14:27:51.498] boot - 981  INFO [http-nio-8090-exec-5] --- UniversalContextSettingFilter: productLine in token is null and session
Id is null[2015-10-23 14:27:51.499] boot - 981  INFO [http-nio-8090-exec-5] --- CacheManagerForResource: query obj from cache with key: RANDOMVALIDATEC
ODEKEY[2015-10-23 14:27:51.500] boot - 981  INFO [http-nio-8090-exec-5] --- CacheManagerForResource: query obj from cache with key: RANDOMVALIDATEC
ODEKEY[2015-10-23 14:27:51.501] boot - 981  INFO [http-nio-8090-exec-5] --- CacheManagerForResource: delete obj from cache with key: RANDOMVALIDATE
CODEKEY[2015-10-23 14:27:51.502] boot - 981  INFO [http-nio-8090-exec-5] --- RequestProxy: connect to file server : [127.0.0.1:9090]
[2015-10-23 14:27:51.502] boot - 981  INFO [http-nio-8090-exec-5] --- RequestProxy: connect to file server : 127.0.0.1 port 9090
[2015-10-23 14:27:51.503] boot - 981  INFO [http-nio-8090-exec-5] --- FileServerClient: request info =====: [command : LS , params : {dir=use
r}][2015-10-23 14:27:51.506] boot - 981  INFO [nioEventLoopGroup-5-1] --- FileServerClient: successfully connect to file server
[2015-10-23 14:27:51.517] boot - 981  INFO [nioEventLoopGroup-5-1] --- FileServerClient: successfuly recieve message from file server [status
 : FAIL, message : 请求路径不存在, datas : {result=fail, msg=请求路径不存在}][2015-10-23 14:27:51.518] boot - 981  INFO [http-nio-8090-exec-5] --- CacheManagerForResource: set obj to cache with key: 4657743689737696
[2015-10-23 14:27:52.215] boot - 981  WARN [http-nio-8090-exec-5] --- ProductLineRegisterServiceImpl: 发送邮件失败:
java.lang.Exception: 发送邮件失败:
        at com.baidu.rigel.biplatform.ma.auth.mail.SendMail.send(SendMail.java:526)
        at com.baidu.rigel.biplatform.ma.auth.service.impl.ProductLineRegisterServiceImpl.sendRegisterMsgToAdministrator(ProductLineRegisterS
erviceImpl.java:154)        at com.baidu.rigel.biplatform.ma.auth.resource.RegisterController.register(RegisterController.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.
java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter
.java:776)        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.jav
a:705)        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.setSessionInfoIntoThread(UniversalContextSettingFilter
.java:216)        at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 Authentication required

        at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:1515)
        at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1054)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:634)
        at com.baidu.rigel.biplatform.ma.auth.mail.SendMail.send(SendMail.java:523)
        ... 53 more
[2015-10-23 14:27:53.948] boot - 981  INFO [http-nio-8090-exec-3] --- UniversalContextSettingFilter: current request url : /silkroad/auth
[2015-10-23 14:27:53.948] boot - 981  INFO [http-nio-8090-exec-3] --- UniversalContextSettingFilter: productLine in cookie is null and sessio
nId is null[2015-10-23 14:27:53.948] boot - 981  INFO [http-nio-8090-exec-3] --- UniversalContextSettingFilter: productLine in token is null and session
Id is null[2015-10-23 14:27:53.951] boot - 981  INFO [http-nio-8090-exec-3] --- CacheManagerForResource: set obj to cache with key: RANDOMVALIDATECODEK
EY[2015-10-23 14:27:55.159] boot - 981 ERROR [regularReportTaskConsumerMessageListenerContainer-1] --- DefaultMessageListenerContainer: Could n
ot refresh JMS Connection for destination 'queue://regularReportTaskQueue' - retrying using FixedBackOff{interval=5000, currentAttempts=2900, maxAttempts=unlimited}. Cause: Error while attempting to add new Connection to the pool; nested exception is javax.jms.JMSException: Could not connect to broker URL: tcp://127.0.0.1:61616. Reason: java.net.ConnectException: Connection refused

**Comment by heropiant** [comment]
现在可以注册帐号了。注册了一个ecparktest 线上 和 一个ecparklocal 线下。

**Comment by wangyuxue** [comment]
@heropiant 收到注册成功邮件后需要开通产品线，开通产品线后在文件服务器的user目录下会有产品线相关信息

**Comment by heropiant** [comment]
开通产品线，是在收到的邮件中点击帐号条目最后的“线上/线下服务”这个吗？我注册的

**Comment by heropiant** [comment]
重新注册了一个帐号，登录进去了。
在user目录里，不能登录的帐号是以一个目录的形式出现的，下面有一个文本文件；能登录的帐号就是在user下直接的一个文本文件。不知道为什么会是完全不同的结构。

**Comment by heropiant** [comment]
怎么关闭JMS-MQ?
现在用是可以用了，但LOG隔几秒就报一次错。

**Comment by wangyuxue** [comment]
需要更新最新代码

**Comment by lss730** [comment]
单机版怎么注册啊？局域网不可以联网的

**Comment by heropiant** [comment]
现在这个时代，内网服务器都可以上网了，否则你会很不方便。

**Comment by majun04** [comment]
@heropiant
要屏蔽JMS-MQ连接日志的话，需要在jvm启动参数加如下信息：
-Dlogging.config=/$your_home$/designer/src/main/resources/conf/log4j.properties
因为基于springboot的启动貌似不能完整的读出log4j.properties里面的日志配置，需要单独增加该参数才可以

**Comment by majun04** [comment]
@lss730
这个目前没太多办法处理，建议先找个有外网的环境（比如回到家里），然后注册用户成功，再回局域网登陆了

**Comment by vblvbl** [comment]
@heropiant  邮件发送异常 你是怎么解决的

**Comment by wangyuxue** [comment]
@vblvbl 看一下邮件服务器地址配置，如需指定用户名、密码，需要配置正确帐号信息
