### ISSUE TITLE
邮件发送失败

### ISSUE THREAD

**Issue by vblvbl** [Baidu-ecom/bi-platform#172]
fileserver designer tesseract都能正常启动，但是注册后designer 日志报错 邮件发送异常

[2016-01-03 14:38:52.893] boot - 17635  INFO [nioEventLoopGroup-3-1] --- FileServerClient: successfuly recieve message from file server [status : FAIL, message : 请求路径不存在, datas : {result=fail, msg=请求路径不存在}]
[2016-01-03 14:38:52.896] boot - 17635  INFO [http-nio-8090-exec-10] --- CacheManagerForResource: set obj to cache with key: 1017473050202734
[2016-01-03 14:38:54.173] boot - 17635  WARN [http-nio-8090-exec-10] --- ProductLineRegisterServiceImpl: 发送邮件失败:
java.lang.Exception: 发送邮件失败:
	at com.baidu.rigel.biplatform.ma.auth.mail.SendMail.send(SendMail.java:526)
	at com.baidu.rigel.biplatform.ma.auth.service.impl.ProductLineRegisterServiceImpl.sendRegisterMsgToAdministrator(ProductLineRegisterServiceImpl.java:154)
	at com.baidu.rigel.biplatform.ma.auth.resource.RegisterController.register(RegisterController.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.setSessionInfoIntoThread(UniversalContextSettingFilter.java:216)
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.mail.AuthenticationFailedException
	at javax.mail.Service.connect(Service.java:319)
	at javax.mail.Service.connect(Service.java:169)
	at com.baidu.rigel.biplatform.ma.auth.mail.SendMail.send(SendMail.java:521)
	... 53 more
[2016-01-03 14:38:56.532] boot - 17635  INFO [http-nio-8090-exec-1] --- UniversalContextSettingFilter: current request url : /silkroad/auth
[2016-01-03 14:38:56.533] boot - 17635  INFO [http-nio-8090-exec-1] --- UniversalContextSettingFilter: productLine in cookie is null and sessionId is null
[2016-01-03 14:38:56.533] boot - 17635  INFO [http-nio-8090-exec-1] --- UniversalContextSettingFilter: productLine in token is null and sessionId is null
[2016-01-03 14:38:56.537] boot - 17635  INFO [http-nio-8090-exec-1] --- CacheManagerForResource: set obj to cache with key: RANDOMVALIDATECODEKEY

**Comment by wangyuxue** [comment]
@vblvbl 麻烦排插一下当前用户对于文件服务器根目录的权限

**Comment by Supanccy** [comment]
1，文件服务器没有配置成功，否则不会报错，请求路径不存在。
2，检查application配置文件中的邮箱是否正确，需要真实的用户，建议在sina上建立账户，进行测试
3，建立完新浪邮箱，进入邮箱里面，点击设置， 打开smtp服务，记住smtp服务为 smtp.sina.com
4，确保你的网络没有限制，如果有限制也会发送邮件失败的。

**Comment by vblvbl** [comment]
@Supanccy  多谢 是没有打开smtp服务
