### ISSUE TITLE
开通线上服务失败

### ISSUE THREAD

**Issue by nckimo** [Baidu-ecom/bi-platform#173]
请教个问题，管理员邮箱收到注册邮件后，点邮件开通线上服务链接失败，错误信息如下：
[2016-01-04 12:13:17.235] boot - 5688  INFO [http-nio-8090-exec-5] --- RequestPr
oxy: connect to file server : [127.0.0.1:9090]
[2016-01-04 12:13:17.239] boot - 5688  INFO [http-nio-8090-exec-5] --- RequestPr
oxy: connect to file server : 127.0.0.1 port 9090
[2016-01-04 12:13:17.246] boot - 5688  INFO [http-nio-8090-exec-5] --- FileServe
rClient: request info =====: [command : MKDIR , params : {dir=MMM}]
[2016-01-04 12:13:18.254] boot - 5688  WARN [http-nio-8090-exec-5] --- ProductLi
neRegisterServiceImpl: failed
com.baidu.rigel.biplatform.api.client.service.FileServiceException: failed
        at com.baidu.rigel.biplatform.api.client.service.impl.FileServiceImpl.mk
dir(FileServiceImpl.java:239)
        at com.baidu.rigel.biplatform.ma.auth.service.impl.ProductLineRegisterSe
rviceImpl.makeDirForOpenService(ProductLineRegisterServiceImpl.java:361)
        at com.baidu.rigel.biplatform.ma.auth.service.impl.ProductLineRegisterSe
rviceImpl.openOnlineService(ProductLineRegisterServiceImpl.java:327)
        at com.baidu.rigel.biplatform.ma.auth.resource.RegisterController.openOn
lineService(RegisterController.java:134)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeF
orRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocabl
eHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingH
andlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapt
er.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(Dispatch
erServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(Dispatche
rServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(Frame
workServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServl
et.java:857)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkSer
vlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52
)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInterna
l(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSetting
Filter.setSessionInfoIntoThread(UniversalContextSettingFilter.java:216)
        at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSetting
Filter.doFilter(UniversalContextSettingFilter.java:116)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern
al(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR
equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:501)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce
ssLogValve.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:516)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:1086)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:659)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.pr
ocess(Http11NioProtocol.java:223)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo
int.java:1558)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoin
t.java:1515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh
read.java:61)
        at java.lang.Thread.run(Unknown Source)
[2016-01-04 12:13:21.895] boot - 5688 ERROR [regularReportTaskConsumerMessageLis
tenerContainer-1] --- DefaultMessageListenerContainer: Could not refresh JMS Con
nection for destination 'queue://regularReportTaskQueue' - retrying using FixedB
ackOff{interval=5000, currentAttempts=15, maxAttempts=unlimited}. Cause: Error w
hile attempting to add new Connection to the pool; nested exception is javax.jms
.JMSException: Could not connect to broker URL: tcp://127.0.0.1:61616. Reason: j
ava.net.ConnectException: Connection refused: connect

**Comment by wangyuxue** [comment]
@nckimo 当前情况下需要你打开的邮箱服务能连上你的平台服务

**Comment by nckimo** [comment]
@wangyuxue 你好，
是可以连接到平台的，点开线上服务连接，返回了下面的信息：
{"statusInfo":"open online service for user [MMM] failed","status":1,"data":null,"properties":{}}

**Comment by wangyuxue** [comment]
@nckimo 你好，请确认一下当前启动fileserver用户是否对fileserver根目录存在755 操作权限，这几天比较忙，未及时回复，抱歉！

**Comment by nckimo** [comment]
@wangyuxue  你好，是有权限的，我是在window下启动的

**Comment by wangyuxue** [comment]
麻烦把designer的配置文件贴一下吧，把path分割修改为 / 还有就是目录之间最好不要有空格

**Comment by nckimo** [comment]
@wangyuxue  designer配置文件内容如下：
server.port=8090
sen
#****************************************************************************************************************
#    the location which the datasource define file stored, that need correct relative path,not absolute path
#NOTICE: the location must exist on the file server and located at the file server default location
#****************************************************************************************************************
biplatform.ma.ds.location=ds

#****************************************************************************************************************
#    the location which the report define file stored, that need correct relative path,not absolute path
#NOTICE: the location must exist on the file server and located at the file server default location
#****************************************************************************************************************
biplatform.ma.report.location=report

# for file-server client end
#****************************************************************************************************************
#the max block size which read from the file server default is 1M
#in current version, this item is not needed
#****************************************************************************************************************
#biplatform.ma.file.read.maxsize=1024

#****************************************************************************************************************
#file server host default is 127.0.0.1
#****************************************************************************************************************
biplatform.ma.fileserver.inetaddress=127.0.0.1:9090

#****************************************************************************************************************
#file server port default value is 9090
#****************************************************************************************************************
#biplatform.ma.fileserver.port=9090

#****************************************************************************************************************
#file server port default value is 9090
#****************************************************************************************************************
biplatform.ma.ser_key=0000000000000000


#****************************************************************************************************************
#jms server url default value is jmsQueue
#****************************************************************************************************************
biplatform.ma.jms.jmsServerUrl=tcp://127.0.0.1:61616

################################################################################################
# schedule service host name 
################################################################################################
biplatform.ma.schedule.hostname=127.0.0.1

################################################################################################
# schedule service host port 
################################################################################################
biplatform.ma.schedule.host.port=8090

################################################################################################
# thread pool size for task execute
################################################################################################
biplatform.ma.schedule.task.thread.pool.size = 5

################################################################################################
# max retry times to write when failed
################################################################################################
biplatform.ma.schedule.task.max.try.times.when.write.failed = 5

################################################################################################
# ????????¨¨???§?§?????????????§?§?????????
################################################################################################
biplatform.ma.regular.report.max.retry.times = 5

################################################################################################
# ??????????§?§???ì???????????????
################################################################################################
biplatform.ma.regular.report.base.dir = regular_report


################################################################################################
# ????????¨¨???§?§?????????§?????????????§?§??
################################################################################################
biplatform.ma.regular.report.mail.receiver =andy.cao@longsys.com

################################################################################################
#           senderMail \u53D1\u9001\u8005\u90AE\u7BB1
#   \u00A0\u6BD4\u5982\uFF1Azhangsan@bi_platform.com
################################################################################################
biplatform.ma.auth.register.mail.senderMail=***@longsys.com

################################################################################################
#   receiverMail \u63A5\u6536\u8005\u90AE\u7BB1
#       \u6BD4\u5982\uFF1Aadmin@163.com
################################################################################################
biplatform.ma.auth.register.mail.administrator=***@longsys.com

################################################################################################
#subject  \u6CE8\u518C\u90AE\u4EF6\u4E3B\u9898
################################################################################################
biplatform.ma.auth.register.mail.subjectForRegister=[\u62A5\u8868\u5E73\u53F0]\u4F7F\u7528\u7533\u8BF7--

################################################################################################
#subject  \u5F00\u901A\u670D\u52A1\u90AE\u4EF6\u4E3B\u9898
################################################################################################

biplatform.ma.auth.register.mail.subjectForOpenService=[\u62A5\u8868\u5E73\u53F0]\u5F00\u901A\u670D\u52A1--
################################################################################################
#       mail server host \u90AE\u4EF6\u670D\u52A1\u5668\u5730\u5740
#           \u6BD4\u5982\uFF1Abi_platform.com
#biplatform.ma.auth.register.mail.mailServerHost=smtp.sina.com.cn
################################################################################################
biplatform.ma.auth.register.mail.mailServerHost=ncex.goodwill-ic.com

################################################################################################
# main send user password
#biplatform.ma.auth.register.mail.sender.password=12345
################################################################################################
biplatform.ma.auth.register.mail.sender.password=******
server.tomcat.uri-encoding=utf8
# log pattern of the access log
server.tomcat.access-log-pattern="%h %l %u %t %r %s %b %{Referer}i %{User-Agent}i %D  
# is access logging enabled
server.tomcat.access-log-enabled=true 
server.tomcat.max-threads=1000
#loging config
logging.config=conf/log4j.properties

schedule.excuteActionUrlHost=http://127.0.0.1:8090/

################################################################################################
# redis cache config
################################################################################################
config.redis.usePool=true
config.redis.password=biplatform
#spring.redis.port=
config.redis.poolConfig.max-idle=8
config.redis.poolConfig.min-idle=0
config.redis.poolConfig.max-active=8
config.redis.poolConfig.max-wait=-1
################################################################################################
#default use redis
################################################################################################
config.redis.active=false

################################################################################################
#mark if this instance is dev
################################################################################################
#config.redis.dev=true

################################################################################################
#redis conifg proeprties
################################################################################################
config.redis.poolConfig.testOnReturn=true
config.redis.poolConfig.testWhileIdle=true
config.redis.poolConfig.testOnBorrow=true
config.redis.poolConfig.testOnCreate=true
config.redis.poolConfig.timeOut=1000

config.redis.topicName=silkroad_topic
config.redis.eventQueueName=silkroad_event_queue
config.redis.lockName=silkroad_lock

################################################################################################
# redis server config
################################################################################################
config.redis.sentinel.master=biplatform_master
config.redis.sentinel.nodes=10.57.204.72:8379

################################################################################################
# schedule module config
################################################################################################
schedule.enable=false


#hazelcast cluster config info
hazelcastServer.groupUserName=silkroad-group
hazelcastServer.groupPassword=silkroad
#hazelcastServer.mancenter.url=
hazelcastServer.mancenter.enable=false
hazelcastServer.members=127.0.0.1
hazelcastServer.portAutoIncrement=false
hazelcastServer.instanceName=silkroad-cluster

spring.velocity.checkTemplateLocation=false
