### ISSUE TITLE
制作报表出错

### ISSUE THREAD

**Issue by justinyao** [Baidu-ecom/bi-platform#199]
好不容易启动了项目，但制作报表又出错了：
@wangyuxue 麻烦帮忙看看啊

[2016-02-24 16:27:21602 ERROR]--http-nio-8090-exec-8--[dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.RuntimeException: productline encrypt happened exception, message:org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: send post failed[http://[127.0.0.1:8020]/query]. params :[question={"cube":{"dimensions":{"area_city":{"tableName":"area","type":"STANDARD_DIMENSION","levels":{"city":{"source":"city","type":"REGULAR","dimTable":"area","factTableColumn":"area_id","id":"a8fed63c372f6c2972226c07b8f89d5a","name":"city","caption":"city","visible":true,"primaryKey":"area_id"}},"facttableColumn":"area_id","facttableCaption":"area_id","id":"81cbc0a99754605f42516f432363e5cd","name":"area_city","caption":"city","visible":true,"primaryKey":"area_id"},"area_prov":{"tableName":"area","type":"STANDARD_DIMENSION","levels":{"prov":{"source":"prov","type":"REGULAR","dimTable":"area","factTableColumn":"area_id","id":"0915cd67268be37adc83bf5b55b04770","name":"prov","caption":"prov","visible":true,"primaryKey":"area_id"}},"facttableColumn":"area_id","facttableCaption":"area_id","id":"11a71ee984c1f76e04e9d397bfc8a5ac","name":"area_prov","caption":"prov","visible":true,"primaryKey":"area_id"}},"measures":{"pay":{"aggregator":"SUM","type":"COMMON","define":"pay","id":"9035736a428ed0d54e3eb0240a04efc4","name":"pay","caption":"pay","visible":true}},"enableCache":true,"source":"cust_pay","mutilple":false,"productLine":"yaojinxu","id":"b7fe11440972d6850424a455b3df8f6e_f3a6793a099c2f493d17f0633d536d84","name":"b7fe11440972d6850424a455b3df8f6e","visible":true},"dataSourceInfo":{"dataSourceKey":"64e3c696c87a22c1a2d43aa44b4216ad","hosts":["172.26.156.21:3306"],"jdbcUrls":["jdbc:mysql://172.26.156.21:3306/e4s_demo?useUniCode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true"],"username":"root","password":"RrPutpXEaGWWwpNm6dbA9w%3D%3D","instanceName":"e4s_demo","isDBProxy":false,"dbPoolInfo":{},"dataBase":"MYSQL","productLine":"yaojinxu","dataSourceType":"SQL"},"axisMetas":{"COLUMN":{"queryMeasures":["pay"],"queryItemsOrder":["[Measure].[pay]"],"axisType":"COLUMN"},"ROW":{"crossjoinDims":["area_city"],"axisType":"ROW"},"FILTER":{"axisType":"FILTER"}},"queryConditions":{"area_city":{"queryDataNodes":[],"metaName":"area_city","metaType":"Dimension","memberSortType":"ASC"}},"requestParams":{"_rbk":"yaojinxu","Cookie":"prevReq=/silkroad/index.html; 01ztb-iq09prpk37_r=0; __utma=96992031.1635731561.1449717838.1449717838.1449717838.1; __utmz=96992031.1449717838.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); AJSTAT_ok_times=4; rememberMe=eZcBmpInjakFId1LzTBM3i9SYCqp206GbWO8gJZpWZM4r0+CQd0o2sRiLsUgRGtAVFp4EeaB22VCFToy0+dsuvvA/zOebaQ4TX5JagVdU/7eaCGLnQ/UsBfkYuu+n18hgaXmY1xGDTxWamnlb1GvbDuwHbpLp1hbMEJ4694eGfMwQpBBIGT58T1ZxEpVZhgzksddBxqFLkJpUSe+UclbdYqj6vDYZgpDHHDH6UC6+Ey600vUB4z6svrWy73hkQKL0gS26cgYlPyzp58+4kk5U9023aox0rSKuOcbQvSld3a+xpZTxu+ciOOGuVw4VKkPNaogS6Wf1g5PIJIgB9AS/VeWayMKTCv/YZykZGqLhNC2e6iFsSnwc5adlbuvgQYeoRnil2RvVlHPyzFwI3vHGj9QRD+Ajsil8DdWT9HzlavCLFZ30174IdN95ma023fDe6mTaiOKImgLiE+jAJ48DlWRniUj13cPJnGtMT8NglXxEQRbw+RlK7N5+ShxOKUEkNPV8IXD2u8rbnYJjBh2Lw==; RANDOMVALIDATECODEKEY=RANDOMVALIDATECODEKEY; biplatform_productline=FTL8nJ2%2B1Y%2BAckGomnSy8g%3D%3D; uniqueFlag=88414752cea321d0e8e9c93b4c19ca6e","phase":"dev","_cltime":"1456302441482","_cltimezone":"-480","componentId":"f3a6793a099c2f493d17f0633d536d84","reportId":"f5d990d56601a9373d591972a82eed84","_V_SRC":"PROD","reportPreview":"true","token":"FTL8nJ2+1Y+AckGomnSy8g=="},"sortRecord":{"sortType":"DESC","sortColumnUniquename":"[Measure].[pay]","recordSize":500},"cubeId":"b7fe11440972d6850424a455b3df8f6e","useCache":true,"queryConditionLimit":{"warnningConditionSize":50000,"warningAtOverFlow":false},"needSummary":false,"isUseIndex":true,"filterBlank":false,"querySource":"TESSERACT","queryId":"28668588515439"}, signature=eb52a21fabe0bcae3851f6b117df2425, token=gpbuVkwk1123kQ6II07obw%3D%3D]
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:138)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.RuntimeException: send post failed[http://[127.0.0.1:8020]/query]. params :[question={"cube":{"dimensions":{"area_city":{"tableName":"area","type":"STANDARD_DIMENSION","levels":{"city":{"source":"city","type":"REGULAR","dimTable":"area","factTableColumn":"area_id","id":"a8fed63c372f6c2972226c07b8f89d5a","name":"city","caption":"city","visible":true,"primaryKey":"area_id"}},"facttableColumn":"area_id","facttableCaption":"area_id","id":"81cbc0a99754605f42516f432363e5cd","name":"area_city","caption":"city","visible":true,"primaryKey":"area_id"},"area_prov":{"tableName":"area","type":"STANDARD_DIMENSION","levels":{"prov":{"source":"prov","type":"REGULAR","dimTable":"area","factTableColumn":"area_id","id":"0915cd67268be37adc83bf5b55b04770","name":"prov","caption":"prov","visible":true,"primaryKey":"area_id"}},"facttableColumn":"area_id","facttableCaption":"area_id","id":"11a71ee984c1f76e04e9d397bfc8a5ac","name":"area_prov","caption":"prov","visible":true,"primaryKey":"area_id"}},"measures":{"pay":{"aggregator":"SUM","type":"COMMON","define":"pay","id":"9035736a428ed0d54e3eb0240a04efc4","name":"pay","caption":"pay","visible":true}},"enableCache":true,"source":"cust_pay","mutilple":false,"productLine":"yaojinxu","id":"b7fe11440972d6850424a455b3df8f6e_f3a6793a099c2f493d17f0633d536d84","name":"b7fe11440972d6850424a455b3df8f6e","visible":true},"dataSourceInfo":{"dataSourceKey":"64e3c696c87a22c1a2d43aa44b4216ad","hosts":["172.26.156.21:3306"],"jdbcUrls":["jdbc:mysql://172.26.156.21:3306/e4s_demo?useUniCode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true"],"username":"root","password":"RrPutpXEaGWWwpNm6dbA9w%3D%3D","instanceName":"e4s_demo","isDBProxy":false,"dbPoolInfo":{},"dataBase":"MYSQL","productLine":"yaojinxu","dataSourceType":"SQL"},"axisMetas":{"COLUMN":{"queryMeasures":["pay"],"queryItemsOrder":["[Measure].[pay]"],"axisType":"COLUMN"},"ROW":{"crossjoinDims":["area_city"],"axisType":"ROW"},"FILTER":{"axisType":"FILTER"}},"queryConditions":{"area_city":{"queryDataNodes":[],"metaName":"area_city","metaType":"Dimension","memberSortType":"ASC"}},"requestParams":{"_rbk":"yaojinxu","Cookie":"prevReq=/silkroad/index.html; 01ztb-iq09prpk37_r=0; __utma=96992031.1635731561.1449717838.1449717838.1449717838.1; __utmz=96992031.1449717838.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); AJSTAT_ok_times=4; rememberMe=eZcBmpInjakFId1LzTBM3i9SYCqp206GbWO8gJZpWZM4r0+CQd0o2sRiLsUgRGtAVFp4EeaB22VCFToy0+dsuvvA/zOebaQ4TX5JagVdU/7eaCGLnQ/UsBfkYuu+n18hgaXmY1xGDTxWamnlb1GvbDuwHbpLp1hbMEJ4694eGfMwQpBBIGT58T1ZxEpVZhgzksddBxqFLkJpUSe+UclbdYqj6vDYZgpDHHDH6UC6+Ey600vUB4z6svrWy73hkQKL0gS26cgYlPyzp58+4kk5U9023aox0rSKuOcbQvSld3a+xpZTxu+ciOOGuVw4VKkPNaogS6Wf1g5PIJIgB9AS/VeWayMKTCv/YZykZGqLhNC2e6iFsSnwc5adlbuvgQYeoRnil2RvVlHPyzFwI3vHGj9QRD+Ajsil8DdWT9HzlavCLFZ30174IdN95ma023fDe6mTaiOKImgLiE+jAJ48DlWRniUj13cPJnGtMT8NglXxEQRbw+RlK7N5+ShxOKUEkNPV8IXD2u8rbnYJjBh2Lw==; RANDOMVALIDATECODEKEY=RANDOMVALIDATECODEKEY; biplatform_productline=FTL8nJ2%2B1Y%2BAckGomnSy8g%3D%3D; uniqueFlag=88414752cea321d0e8e9c93b4c19ca6e","phase":"dev","_cltime":"1456302441482","_cltimezone":"-480","componentId":"f3a6793a099c2f493d17f0633d536d84","reportId":"f5d990d56601a9373d591972a82eed84","_V_SRC":"PROD","reportPreview":"true","token":"FTL8nJ2+1Y+AckGomnSy8g=="},"sortRecord":{"sortType":"DESC","sortColumnUniquename":"[Measure].[pay]","recordSize":500},"cubeId":"b7fe11440972d6850424a455b3df8f6e","useCache":true,"queryConditionLimit":{"warnningConditionSize":50000,"warningAtOverFlow":false},"needSummary":false,"isUseIndex":true,"filterBlank":false,"querySource":"TESSERACT","queryId":"28668588515439"}, signature=eb52a21fabe0bcae3851f6b117df2425, token=gpbuVkwk1123kQ6II07obw%3D%3D]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.setSessionInfoIntoThread(UniversalContextSettingFilter.java:364)
	at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:136)
	... 23 more
Caused by: java.lang.RuntimeException: send post failed[http://[127.0.0.1:8020]/query]. params :[question={"cube":{"dimensions":{"area_city":{"tableName":"area","type":"STANDARD_DIMENSION","levels":{"city":{"source":"city","type":"REGULAR","dimTable":"area","factTableColumn":"area_id","id":"a8fed63c372f6c2972226c07b8f89d5a","name":"city","caption":"city","visible":true,"primaryKey":"area_id"}},"facttableColumn":"area_id","facttableCaption":"area_id","id":"81cbc0a99754605f42516f432363e5cd","name":"area_city","caption":"city","visible":true,"primaryKey":"area_id"},"area_prov":{"tableName":"area","type":"STANDARD_DIMENSION","levels":{"prov":{"source":"prov","type":"REGULAR","dimTable":"area","factTableColumn":"area_id","id":"0915cd67268be37adc83bf5b55b04770","name":"prov","caption":"prov","visible":true,"primaryKey":"area_id"}},"facttableColumn":"area_id","facttableCaption":"area_id","id":"11a71ee984c1f76e04e9d397bfc8a5ac","name":"area_prov","caption":"prov","visible":true,"primaryKey":"area_id"}},"measures":{"pay":{"aggregator":"SUM","type":"COMMON","define":"pay","id":"9035736a428ed0d54e3eb0240a04efc4","name":"pay","caption":"pay","visible":true}},"enableCache":true,"source":"cust_pay","mutilple":false,"productLine":"yaojinxu","id":"b7fe11440972d6850424a455b3df8f6e_f3a6793a099c2f493d17f0633d536d84","name":"b7fe11440972d6850424a455b3df8f6e","visible":true},"dataSourceInfo":{"dataSourceKey":"64e3c696c87a22c1a2d43aa44b4216ad","hosts":["172.26.156.21:3306"],"jdbcUrls":["jdbc:mysql://172.26.156.21:3306/e4s_demo?useUniCode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true"],"username":"root","password":"RrPutpXEaGWWwpNm6dbA9w%3D%3D","instanceName":"e4s_demo","isDBProxy":false,"dbPoolInfo":{},"dataBase":"MYSQL","productLine":"yaojinxu","dataSourceType":"SQL"},"axisMetas":{"COLUMN":{"queryMeasures":["pay"],"queryItemsOrder":["[Measure].[pay]"],"axisType":"COLUMN"},"ROW":{"crossjoinDims":["area_city"],"axisType":"ROW"},"FILTER":{"axisType":"FILTER"}},"queryConditions":{"area_city":{"queryDataNodes":[],"metaName":"area_city","metaType":"Dimension","memberSortType":"ASC"}},"requestParams":{"_rbk":"yaojinxu","Cookie":"prevReq=/silkroad/index.html; 01ztb-iq09prpk37_r=0; __utma=96992031.1635731561.1449717838.1449717838.1449717838.1; __utmz=96992031.1449717838.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); AJSTAT_ok_times=4; rememberMe=eZcBmpInjakFId1LzTBM3i9SYCqp206GbWO8gJZpWZM4r0+CQd0o2sRiLsUgRGtAVFp4EeaB22VCFToy0+dsuvvA/zOebaQ4TX5JagVdU/7eaCGLnQ/UsBfkYuu+n18hgaXmY1xGDTxWamnlb1GvbDuwHbpLp1hbMEJ4694eGfMwQpBBIGT58T1ZxEpVZhgzksddBxqFLkJpUSe+UclbdYqj6vDYZgpDHHDH6UC6+Ey600vUB4z6svrWy73hkQKL0gS26cgYlPyzp58+4kk5U9023aox0rSKuOcbQvSld3a+xpZTxu+ciOOGuVw4VKkPNaogS6Wf1g5PIJIgB9AS/VeWayMKTCv/YZykZGqLhNC2e6iFsSnwc5adlbuvgQYeoRnil2RvVlHPyzFwI3vHGj9QRD+Ajsil8DdWT9HzlavCLFZ30174IdN95ma023fDe6mTaiOKImgLiE+jAJ48DlWRniUj13cPJnGtMT8NglXxEQRbw+RlK7N5+ShxOKUEkNPV8IXD2u8rbnYJjBh2Lw==; RANDOMVALIDATECODEKEY=RANDOMVALIDATECODEKEY; biplatform_productline=FTL8nJ2%2B1Y%2BAckGomnSy8g%3D%3D; uniqueFlag=88414752cea321d0e8e9c93b4c19ca6e","phase":"dev","_cltime":"1456302441482","_cltimezone":"-480","componentId":"f3a6793a099c2f493d17f0633d536d84","reportId":"f5d990d56601a9373d591972a82eed84","_V_SRC":"PROD","reportPreview":"true","token":"FTL8nJ2+1Y+AckGomnSy8g=="},"sortRecord":{"sortType":"DESC","sortColumnUniquename":"[Measure].[pay]","recordSize":500},"cubeId":"b7fe11440972d6850424a455b3df8f6e","useCache":true,"queryConditionLimit":{"warnningConditionSize":50000,"warningAtOverFlow":false},"needSummary":false,"isUseIndex":true,"filterBlank":false,"querySource":"TESSERACT","queryId":"28668588515439"}, signature=eb52a21fabe0bcae3851f6b117df2425, token=gpbuVkwk1123kQ6II07obw%3D%3D]
	at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:306)
	at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:330)
	at com.baidu.rigel.biplatform.ac.query.MiniCubeSqlConnection.query(MiniCubeSqlConnection.java:81)
	at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatasHelper(ReportModelQueryServiceImpl.java:278)
	at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatas(ReportModelQueryServiceImpl.java:228)
	at com.baidu.rigel.biplatform.ma.resource.QueryDataResource.queryArea(QueryDataResource.java:242)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	... 38 more

**Comment by wangyuxue** [comment]
@justinyao 从日志上看是请求发送到queryrouter报错，麻烦贴一下query router日志吧
