### ISSUE TITLE
设计报表时出错

### ISSUE THREAD

**Issue by smallgoldstone** [Baidu-ecom/bi-platform#201]
使用的1.6.1，ac.properties文件
server.queryrouter.address=http://[127.0.0.1:8020]/queryrouter
server.queryrouter.systemcode=biplatform
server.queryrouter.systemkey=biplatform
server.tesseract.address=http://[127.0.0.1:8080]
在横轴和纵轴添上内容后，提示系统异常。log中报
Caused by: java.lang.NullPointerException
        at com.baidu.rigel.biplatform.ac.util.HttpRequest$ClientInstance.getRoutee(HttpRequest.java:479)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest$ClientInstance.getClientInstance(HttpRequest.java:460)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest.getDefaultHttpClient(HttpRequest.java:108)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:313)
        at com.baidu.rigel.biplatform.ac.query.MiniCubeSqlConnection.query(MiniCubeSqlConnection.java:99)
        at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatasHelper(ReportModelQueryServiceImpl.java:272)
        at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatas(ReportModelQueryServiceImpl.java:220)
        at com.baidu.rigel.biplatform.ma.resource.QueryDataResource.queryArea(QueryDataResource.java:1235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
请问，我应该怎样解决？

**Comment by wangyuxue** [comment]
@smallgoldstone 请将配置文件中tesseract中相关配置注释掉

**Comment by smallgoldstone** [comment]
删除了以后，报的异常是一样的

**Comment by smallgoldstone** [comment]
我启动用的脚本，是启动中有配置文件缺失或者启动顺序问题吗？
$JAVA_HOME/bin/java -jar $BI_HOME/lib/fileserver-1.6.1-RELEASE.jar $BI_HOME/conf/fileserver.conf > $BI_HOME/log/fileserver.log &
sleep 10
$JAVA_HOME/bin/java -jar $BI_HOME/lib/queryrouter-1.6.1-RELEASE.jar -Dbiplatform.auth.server=$BI_HOME/conf/auth_server.properties -Dserver.port=8020 -Xmx1028m > $BI_HOME/log/queryrouter.log &
sleep 30
$JAVA_HOME/bin/java -jar $BI_HOME/lib/designer-1.6.1-RELEASE.jar -Dac.config.location=$BI_HOME/conf/ac.properties -Dserver.port=8090 > $BI_HOME/log/designer.log &
sleep 30
$JAVA_HOME/bin/java -jar $BI_HOME/lib/tesseract-1.6.1-RELEASE.jar -Xmx4096m -Xms4096m  -Dserver.port=8080 -Dac.config.location=$BI_HOME/conf/ac.properties > $BI_HOME/log/tesseract.log &
