### ISSUE TITLE
2.0.0分支注册出现null的提示，有人有遇到这样的情况吗?

### ISSUE THREAD

**Issue by gm504117608** [Baidu-ecom/bi-platform#218]
后端错误日志信息如下：
[2016-07-13 11:13:25.986] boot - 6656  INFO [http-nio-8091-exec-5] --- RequestProxy: connect to file server : [127.0.0.1:9090]
[2016-07-13 11:13:25.986] boot - 6656  INFO [http-nio-8091-exec-5] --- RequestProxy: connect to file server : 127.0.0.1 port 9090
[2016-07-13 11:13:25.993] boot - 6656  INFO [http-nio-8091-exec-5] --- FileServerClient: request info =====: [command : LS , params : {dir=user}]
[2016-07-13 11:13:25.994] boot - 6656 ERROR [http-nio-8091-exec-5] --- RequestProxy: io.netty.bootstrap.Bootstrap.channel(Ljava/lang/Class;)Lio/netty/bootstrap/AbstractBootstrap;
java.lang.NoSuchMethodError: io.netty.bootstrap.Bootstrap.channel(Ljava/lang/Class;)Lio/netty/bootstrap/AbstractBootstrap;
    at com.baidu.rigel.biplatform.api.client.service.impl.FileServerClient.doRequest(FileServerClient.java:126)
    at com.baidu.rigel.biplatform.api.client.service.impl.RequestProxy.doRequest(RequestProxy.java:103)
    at com.baidu.rigel.biplatform.api.client.service.impl.RequestProxy.doActionOnRemoteFileSystem(RequestProxy.java:74)
    at com.baidu.rigel.biplatform.api.client.service.impl.FileServiceImpl.ls(FileServiceImpl.java:377)
    at com.baidu.rigel.biplatform.ma.auth.service.impl.ProductLineManageServiceImpl.existsFile(ProductLineManageServiceImpl.java:124)
    at com.baidu.rigel.biplatform.ma.auth.service.impl.ProductLineManageServiceImpl.existsUser(ProductLineManageServiceImpl.java:112)
    at com.baidu.rigel.biplatform.ma.auth.resource.RegisterController.register(RegisterController.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.setSessionInfoIntoThread(UniversalContextSettingFilter.java:364)
    at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:136)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
    at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)

**Comment by jonahLD** [comment]
你好,2.0.0分支（刚下载），我mvn install 时，`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project queryrouter: Compilation failure: Compilation failure:
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/queryplugin/utils/QueryHandlerBuilder.java:[18,76] 程序包com.baidu.rigel.biplatform.queryrouter.queryplugin.plugins.druid.sql不存在
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/QueryRouterApplication4Enterprise.java:[47,70] 找不到符号
[ERROR] 符号:   类 SecurityFilter
[ERROR] 位置: 程序包 com.baidu.rigel.biplatform.queryrouter.handle.manager.security
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/queryplugin/utils/QueryHandlerBuilder.java:[165,37] 找不到符号
[ERROR] 符号:   类 DruidSqlExpression
[ERROR] 位置: 类 com.baidu.rigel.biplatform.queryrouter.queryplugin.utils.QueryHandlerBuilder
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/QueryRouterApplication4Enterprise.java:[106,9] 找不到符号
[ERROR] 符号:   类 SecurityFilter
[ERROR] 位置: 类 com.baidu.rigel.biplatform.queryrouter.QueryRouterApplication4Enterprise
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/QueryRouterApplication4Enterprise.java:[106,44] 找不到符号
[ERROR] 符号:   类 SecurityFilter
[ERROR] 位置: 类 com.baidu.rigel.biplatform.queryrouter.QueryRouterApplication4Enterprise
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/QueryRouterApplication4Enterprise.java:[158,35] 程序包SecurityFilter不存在
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :queryrouter`

你是如何解决的？

**Comment by binggebest** [comment]
@jonahLD  SecurityFilter  这个类不存在的  你找到报错的地方 在代码里把有关这个类的代码都注释掉就好了

**Comment by jonahLD** [comment]
@gm504117608 谢谢，你的跑起来了么？

**Comment by binggebest** [comment]
@jonahLD  queryrouter 启动不了 报表出不来 其他还好

**Comment by binggebest** [comment]
@jonahLD    SecurityFilter  这个类需要自己添加 #220  里 我写了     我的现在跑起来了

**Comment by jonahLD** [comment]
我添加了类SecurityFilter 这个类，还是有个问题
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project queryrouter: Compilation failure: Compilation failure:
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/queryplugin/utils/QueryHandlerBuilder.java:[18,76] 程序包com.baidu.rigel.biplatform.queryrouter.queryplugin.plugins.druid.sql不存在
[ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/queryplugin/utils/QueryHandlerBuilder.java:[165,37] 找不到符号
[ERROR] 符号:   类 DruidSqlExpression
[ERROR] 位置: 类 com.baidu.rigel.biplatform.queryrouter.queryplugin.utils.QueryHandlerBuilder
[ERROR] -> [Help 1]`

你也是通过注释掉的方式解决的么？

**Comment by binggebest** [comment]
@jonahLD  druid 注释掉
