### ISSUE TITLE
queryrouter 无法启动

### ISSUE THREAD

**Issue by binggebest** [Baidu-ecom/bi-platform#220]
ac.properties  我的配置如下
server.queryrouter.address=http://[127.0.0.1:8020]/queryrouter
server.queryrouter.systemcode=biplatform
server.queryrouter.systemkey=biplatfor 

但是设计报表的时候后端报错
org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:8020 [/127.0.0.1] failed: Connection refused: connect
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:298)
        at com.baidu.rigel.biplatform.ac.util.HttpRequest.sendPost(HttpRequest.java:330)
        at com.baidu.rigel.biplatform.ac.query.MiniCubeSqlConnection.query(MiniCubeSqlConnection.java:81)
        at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatasHelper(ReportModelQueryServiceImpl.java:280)
        at com.baidu.rigel.biplatform.ma.report.service.impl.ReportModelQueryServiceImpl.queryDatas(ReportModelQueryServiceImpl.java:239)
        at com.baidu.rigel.biplatform.ma.resource.QueryDataResource.queryArea(QueryDataResource.java:241)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.setSessionInfoIntoThread(UniversalContextSettingFilter.java:364)
        at com.baidu.rigel.biplatform.ma.resource.filter.UniversalContextSettingFilter.doFilter(UniversalContextSettingFilter.java:136)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
        ... 67 more

8020 端口也没有启动 求ac.properties 的具体配置过程啊  求大神   queryrouter  注释了部分代码  已经构建成功了  但是  在quertyrouter 里 无法启动  designer 也无法启动求大神啊求大神

**Comment by binggebest** [comment]
单独启动queryrouter 报错
[2016-07-21 18:37:0982 INFO] -- TomcatEmbeddedServletContainer: Tomcat initialized with port(s): 8020 (http)
[2016-07-21 18:37:09272 INFO] -- StandardService: Starting service Tomcat
[2016-07-21 18:37:09275 INFO] -- StandardEngine: Starting Servlet Engine: Apache Tomcat/8.0.20
[2016-07-21 18:37:09380 INFO] -- [/]: Initializing Spring embedded WebApplicationContext
[2016-07-21 18:37:09380 INFO] -- ContextLoader: Root WebApplicationContext: initialization completed in 2295 ms
[2016-07-21 18:37:1063 INFO] -- FilterRegistrationBean: Mapping filter: 'characterEncodingFilter' to: [/*]
[2016-07-21 18:37:1064 ERROR] -- TomcatStarter: Error starting Tomcat context: java.lang.IllegalArgumentException
[2016-07-21 18:37:10115 WARN] -- AnnotationConfigEmbeddedWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.baidu.rigel.biplatform.queryrouter.QueryRouterApplication4Enterprise.main(QueryRouterApplication4Enterprise.java:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.initialize(TomcatEmbeddedServletContainer.java:98)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.<init>(TomcatEmbeddedServletContainer.java:75)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getTomcatEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:378)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainerFactory.getEmbeddedServletContainer(TomcatEmbeddedServletContainerFactory.java:155)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:157)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: Filter must not be null

**Comment by binggebest** [comment]
Filter must not be null  解决 需要增加SecurityFilter.java到对应目录上
SecurityFilter.java   内容
package com.baidu.rigel.biplatform.queryrouter.handle.manager.security;

import java.io.IOException;
import java.util.Map;
import java.util.Set;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.baidu.rigel.biplatform.ac.util.AesUtil;
import com.google.common.collect.Maps;
import com.google.common.collect.Sets;

public class SecurityFilter implements Filter{
	 private Logger logger = LoggerFactory.getLogger(SecurityFilter.class);
	 public static  Map REPOSITORY = Maps.newConcurrentMap();
	 public static final String TOKEN = "token";
	 public static final String KEY = "key";
	 public SecurityFilter() {
	 }
	 

	@Override
	public void init(FilterConfig filterConfig) throws ServletException {
		// TODO Auto-generated method stub
		
	}
	private boolean isExcludeUrl(String requestURI) { 
		Set excludeUrl = Sets.newHashSet (); 
		excludeUrl.add ("/alive"); 
		return excludeUrl.contains (requestURI); 
		}

	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
			throws IOException, ServletException {
		// TODO Auto-generated method stub
		HttpServletRequest httpRequest = null; httpRequest = (HttpServletRequest) request; 
		// 不需要鉴权的请求 
		String realRequestUri = httpRequest.getRequestURI().substring(1); 
		String requestURI = realRequestUri.substring(realRequestUri.indexOf("/"), realRequestUri.length()); 
		if (isExcludeUrl (requestURI)) { chain.doFilter (request, response); 
			return; 
		} 
		if (doAuth(httpRequest, (HttpServletResponse) response)) { 
			chain.doFilter(httpRequest, response); 
		} 
		
	}
	private boolean doAuth(HttpServletRequest request, HttpServletResponse response) { 
		// 进行认证 
		try { 
			if (request.getParameter(TOKEN) == null) {
				return false; 
				} 
			String systemCodeEncrypt = request.getParameter(TOKEN).toString(); 
			ApiDesAuthService service = new ApiDesAuthService(); 
			String systemCode = AesUtil.getInstance().decodeAnddecrypt(systemCodeEncrypt); 
			JSONObject systemKey = new JSONObject();
			systemKey.put("key", "biplatform");
			/*JSONObject systemKey =  (JSONObject) REPOSITORY.get(systemCode); */
/*			if (systemKey == null) { 
				throw new IllegalStateException("token:\"" + systemKey + "\" is uncorrect, access to services prohibited."); 
				} */
			// 认证请求成功 
			return service.auth(request, response, systemKey.getString(KEY)); 
			} catch (Exception e) { 
				logger.error(e.getMessage()); 
				throw new IllegalStateException("token is uncorrect, authentication failure."); 
				} 
		}

	@Override
	public void destroy() {
		// TODO Auto-generated method stub
		
	}
	

}
