### ISSUE TITLE
eclispe下启动designer报错

### ISSUE THREAD

**Issue by kjbwonder** [Baidu-ecom/bi-platform#229]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/kongjianbo/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/kongjianbo/.m2/repository/org/slf4j/slf4j-log4j12/1.7.11/slf4j-log4j12-1.7.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Exception in thread "main" java.lang.IllegalAccessError: tried to access method org.springframework.core.io.support.SpringFactoriesLoader.loadFactoryNames(Ljava/lang/Class;Ljava/lang/ClassLoader;)Ljava/util/List; from class org.springframework.boot.SpringApplication
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:367)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:358)
	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:230)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:206)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at com.baidu.rigel.biplatform.ma.BiPlatformApplication.main(BiPlatformApplication.java:62)

**Comment by wangyuxue** [comment]
clean ，重新build一下

**Comment by kjbwonder** [comment]
@wangyuxue 试了还是报同样的错误。我试了不用eclipse启动，用本地命令方式启动jar包还是报这个错误。是springboot哪边的jar包版本有问题吗？
