### ISSUE TITLE
线上服务开通问题

### ISSUE THREAD

**Issue by shangqingbai** [Baidu-ecom/bi-platform#231]
我在邮件中点击线上服务连接，下载的内容为：{"statusInfo":"已经开通，不能重复开通","status":1,"data":null,"properties":{}}，我又多次更换用户名进行注册，每次点击链接都是如上信息，始终无法开通，不清楚到底是怎么回事了，请指点一下吧，谢谢。

**Comment by wangyuxue** [comment]
检查一下是不是在文件服务相关目录下已经存在指定文件夹

**Comment by wangyuxue** [comment]
最好能提供后台创建use的相关日志

**Comment by shangqingbai** [comment]
应该是启动的问题，tesseract.jar，designer.jar都要使用8090端口，无法谁先启动，另一个就报端口占用，搞不清楚是怎么回事，之前之所以能启动，是因为我先启动tesseract.jar这个，再修改application.properties文件的端口，然后再启动designer.jar就能启动，估计是不是这么干有问题啊，
启动命令如下：
java -jar designer.jar -Dserver.port=8090 -Dac.config.location=D:\BI\bi-platform-branch_2.0.0\
java -jar tesseract.jar -Xmx2048m -Xms2048m  -Dserver.port=8081 -Dac.config.location=D:\BI\bi-platform-branch_2.0.0\
designer.jar启动报错日志：
[2016-12-16 16:40:24.413] boot - 36508  INFO [main] --- DefaultLifecycleProcessor: Starting beans in phase 2147483647
[2016-12-16 16:40:24.487] boot - 36508 ERROR [main] --- Http11NioProtocol: Failed to start end point associated with Pro
tocolHandler ["http-nio-8090"]
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:343)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:739)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:472)
        at org.apache.coyote.http11.Http11NioProtocol.start(Http11NioProtocol.java:81)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:237)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnector
s(TomcatEmbeddedServletContainer.java:186)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCo
ntainer.java:149)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(Embedde
dWebApplicationContext.java:288)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationC
ontext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext
.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.baidu.rigel.biplatform.ma.BiPlatformApplication.main(BiPlatformApplication.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
[2016-12-16 16:40:24.498] boot - 36508 ERROR [main] --- StandardService: Failed to start connector [Connector[HTTP/1.1-8
090]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8090]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:237)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnector
s(TomcatEmbeddedServletContainer.java:186)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCo
ntainer.java:149)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(Embedde
dWebApplicationContext.java:288)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationC
ontext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext
.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.baidu.rigel.biplatform.ma.BiPlatformApplication.main(BiPlatformApplication.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:993)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 18 more
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:343)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:739)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:472)
        at org.apache.coyote.http11.Http11NioProtocol.start(Http11NioProtocol.java:81)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:986)
        ... 19 more
[2016-12-16 16:40:24.527] boot - 36508  INFO [main] --- StandardService: Stopping service Tomcat
[2016-12-16 16:40:24.551] boot - 36508  WARN [localhost-startStop-2] --- WebappClassLoaderBase: The web application [ROO
T] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very
likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
[2016-12-16 16:40:24.567] boot - 36508  INFO [main] --- ClasspathLoggingApplicationListener: Application failed to start
 with classpath: [jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/desi
gner.jar!/lib/cache-2.0.0-SNAPSHOT.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-boot-starter
-redis-1.2.3.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-context-support-4.1.6.RELE
ASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-tx-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-
platform-branch_2.0.0/designer.jar!/lib/commons-io-2.4.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib
/hazelcast-3.2.3.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/annotations-1.3.2.jar!/, jar:file:/D:
/BI/bi-platform-branch_2.0.0/designer.jar!/lib/hazelcast-client-3.2.3.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/de
signer.jar!/lib/hazelcast-spring-3.2.3.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/redisson-1.2.0.
jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/netty-buffer-4.0.25.Final.jar!/, jar:file:/D:/BI/bi-pl
atform-branch_2.0.0/designer.jar!/lib/netty-common-4.0.25.Final.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer
.jar!/lib/netty-transport-4.0.25.Final.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/netty-handler-4
.0.25.Final.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/netty-codec-http-4.0.25.Final.jar!/, jar:f
ile:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/netty-codec-4.0.25.Final.jar!/, jar:file:/D:/BI/bi-platform-branch
_2.0.0/designer.jar!/lib/slf4j-api-1.7.11.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/jackson-core
-2.4.5.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/jedis-2.5.2.jar!/, jar:file:/D:/BI/bi-platform-
branch_2.0.0/designer.jar!/lib/commons-pool2-2.2.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/sprin
g-data-redis-1.4.2.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-context-4.1.6.RELEAS
E.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-aop-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-p
latform-branch_2.0.0/designer.jar!/lib/aopalliance-1.0.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib
/schedule-2.0.0-SNAPSHOT.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/quartz-2.1.7.jar!/, jar:file:
/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/c3p0-0.9.1.1.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.
jar!/lib/common-api-2.0.0-SNAPSHOT.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/fileserver-2.0.0-SN
APSHOT.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/netty-all-4.0.23.Final.jar!/, jar:file:/D:/BI/b
i-platform-branch_2.0.0/designer.jar!/lib/spring-jms-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/desig
ner.jar!/lib/spring-beans-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-messagi
ng-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/activemq-broker-5.10.0.jar!/, jar:fil
e:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/activemq-openwire-legacy-5.10.0.jar!/, jar:file:/D:/BI/bi-platform-b
ranch_2.0.0/designer.jar!/lib/activemq-client-5.10.0.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/g
eronimo-jms_1.1_spec-1.1.1.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/hawtbuf-1.10.jar!/, jar:fil
e:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar!/, jar:file:/D:/BI/bi-pl
atform-branch_2.0.0/designer.jar!/lib/activemq-jms-pool-5.10.0.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.
jar!/lib/geronimo-jta_1.0.1B_spec-1.0.1.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/commons-pool-1
.6.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/activemq-pool-5.10.0.jar!/, jar:file:/D:/BI/bi-plat
form-branch_2.0.0/designer.jar!/lib/model-2.0.0-SNAPSHOT.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/l
ib/httpclient-4.3.6.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/httpcore-4.3.3.jar!/, jar:file:/D:
/BI/bi-platform-branch_2.0.0/designer.jar!/lib/commons-codec-1.6.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designe
r.jar!/lib/commons-logging-1.1.1.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-boot-starter-w
eb-1.2.3.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-boot-starter-1.2.3.RELEASE.jar
!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-boot-1.2.3.RELEASE.jar!/, jar:file:/D:/BI/bi-platf
orm-branch_2.0.0/designer.jar!/lib/spring-boot-autoconfigure-1.2.3.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0
.0/designer.jar!/lib/snakeyaml-1.14.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-boot-starte
r-tomcat-1.2.3.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/tomcat-embed-core-8.0.20.jar!/,
 jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/tomcat-embed-el-8.0.20.jar!/, jar:file:/D:/BI/bi-platform-br
anch_2.0.0/designer.jar!/lib/tomcat-embed-logging-juli-8.0.20.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.j
ar!/lib/tomcat-embed-websocket-8.0.20.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/jackson-databind
-2.4.5.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/jackson-annotations-2.4.3.jar!/, jar:file:/D:/B
I/bi-platform-branch_2.0.0/designer.jar!/lib/hibernate-validator-5.1.3.Final.jar!/, jar:file:/D:/BI/bi-platform-branch_2
.0.0/designer.jar!/lib/validation-api-1.1.0.Final.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/jbos
s-logging-3.1.3.GA.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/classmate-1.0.0.jar!/, jar:file:/D:
/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-core-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0
/designer.jar!/lib/spring-web-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-web
mvc-4.1.6.RELEASE.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-expression-4.1.6.RELEASE.jar!
/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/spring-boot-starter-log4j-1.2.3.RELEASE.jar!/, jar:file:/D
:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/jcl-over-slf4j-1.7.11.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/de
signer.jar!/lib/jul-to-slf4j-1.7.11.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/slf4j-log4j12-1.7.
11.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/log4j-1.2.17.jar!/, jar:file:/D:/BI/bi-platform-bra
nch_2.0.0/designer.jar!/lib/gson-2.2.2.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/h2-1.4.185.jar!
/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/guava-11.0.2.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0
.0/designer.jar!/lib/jsr305-1.3.9.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/json-20090211.jar!/,
 jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/commons-lang-2.4.jar!/, jar:file:/D:/BI/bi-platform-branch_2
.0.0/designer.jar!/lib/mysql-connector-java-5.1.34.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/com
mons-collections-3.2.2.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/mail-1.4.1.jar!/, jar:file:/D:/
BI/bi-platform-branch_2.0.0/designer.jar!/lib/activation-1.1.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.ja
r!/lib/velocity-1.7.jar!/, jar:file:/D:/BI/bi-platform-branch_2.0.0/designer.jar!/lib/junit-4.11.jar!/, jar:file:/D:/BI/
bi-platform-branch_2.0.0/designer.jar!/lib/hamcrest-core-1.3.jar!/]
[2016-12-16 16:40:24.587] boot - 36508  INFO [main] --- AutoConfigurationReportLoggingInitializer:

Error starting ApplicationContext. To display the auto-configuration report enabled debug logging (start with --debug)


[2016-12-16 16:40:24.591] boot - 36508 ERROR [main] --- SpringApplication: Application startup failed
java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCo
ntainer.java:157)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(Embedde
dWebApplicationContext.java:288)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationC
ontext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext
.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.baidu.rigel.biplatform.ma.BiPlatformApplication.main(BiPlatformApplication.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
[2016-12-16 16:40:24.598] boot - 36508  INFO [main] --- AnnotationConfigEmbeddedWebApplicationContext: Closing org.sprin
gframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@73126b17: startup date [Fri Dec 16 16:40:
05 CST 2016]; root of context hierarchy
[2016-12-16 16:40:24.601] boot - 36508  INFO [main] --- DefaultLifecycleProcessor: Stopping beans in phase 2147483647
[2016-12-16 16:40:24.604] boot - 36508  INFO [main] --- AnnotationMBeanExporter: Unregistering JMX-exposed beans on shut
down
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletCo
ntainer.java:157)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(Embedde
dWebApplicationContext.java:288)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationC
ontext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:483)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext
.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
        at com.baidu.rigel.biplatform.ma.BiPlatformApplication.main(BiPlatformApplication.java:62)
        ... 6 more

**Comment by shangqingbai** [comment]
还想再问一下我的fileserver.jar这样算是启动成功吗
D:\BI\bi-platform-branch_2.0.0>java -jar fileserver.jar D:\BI\bi-platform-branch_2.0.0\fileserver.conf
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
十二月 16, 2016 1:17:18 下午 io.netty.handler.logging.LoggingHandler channelRegistered
信息: [id: 0x5466de0c] REGISTERED
十二月 16, 2016 1:17:18 下午 io.netty.handler.logging.LoggingHandler bind
信息: [id: 0x5466de0c] BIND: 0.0.0.0/0.0.0.0:9060
十二月 16, 2016 1:17:18 下午 io.netty.handler.logging.LoggingHandler channelActive
信息: [id: 0x5466de0c, /0:0:0:0:0:0:0:0:9060] ACTIVE

**Comment by wangyuxue** [comment]
是的

**Comment by wangyuxue** [comment]
是的
